const allTeams = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "South Korea",
  "North Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao",
  "Latvia",
  "Lebanon",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russia",
  "Rwanda",
  "Réunion",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "England",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Anaheim Ducks",
  "Arizona Coyotes",
  "Boston Bruins",
  "Buffalo Sabres",
  "Calgary Flames",
  "Carolina Hurricanes",
  "Chicago Blackhawks",
  "Colorado Avalanche",
  "Columbus Blue Jackets",
  "Dallas Stars",
  "Detroit Red Wings",
  "Edmonton Oilers",
  "Florida Panthers",
  "Los Angeles Kings",
  "Minnesota Wild",
  "Montreal Canadiens",
  "Nashville Predators",
  "New Jersey Devils",
  "New York Islanders",
  "New York Rangers",
  "Ottawa Senators",
  "Philadelphia Flyers",
  "Pittsburgh Penguins",
  "San Jose Sharks",
  "Seattle Kraken",
  "St Louis Blues",
  "Tampa Bay Lightning",
  "Toronto Maple Leafs",
  "Vancouver Canucks",
  "Vegas Golden Knights",
  "Washington Capitals",
  "Winnipeg Jets",
  "Atlanta Hawks",
  "Boston Celtics",
  "Brooklyn Nets",
  "Charlotte Hornets",
  "Chicago Bulls",
  "Cleveland Cavaliers",
  "Dallas Mavericks",
  "Denver Nuggets",
  "Detroit Pistons",
  "Golden State Warriors",
  "Houston Rockets",
  "Indiana Pacers",
  "Los Angeles Clippers",
  "Los Angeles Lakers",
  "Memphis Grizzlies",
  "Miami Heat",
  "Milwaukee Bucks",
  "Minnesota Timberwolves",
  "New Orleans Pelicans",
  "New York Knicks",
  "Oklahoma City Thunder",
  "Orlando Magic",
  "Philadelphia 76ers",
  "Phoenix Suns",
  "Portland Trail Blazers",
  "Sacramento Kings",
  "San Antonio Spurs",
  "Toronto Raptors",
  "Utah Jazz",
  "Washington Wizards",
  "Arizona Cardinals",
  "Atlanta Falcons",
  "Baltimore Ravens",
  "Buffalo Bills",
  "Carolina Panthers",
  "Chicago Bears",
  "Cincinnati Bengals",
  "Cleveland Browns",
  "Dallas Cowboys",
  "Denver Broncos",
  "Detroit Lions",
  "Green Bay Packers",
  "Houston Texans",
  "Indianapolis Colts",
  "Jacksonville Jaguars",
  "Kansas City Chiefs",
  "Las Vegas Raiders",
  "Los Angeles Chargers",
  "Los Angeles Rams",
  "Miami Dolphins",
  "Minnesota Vikings",
  "New England Patriots",
  "New Orleans Saints",
  "New York Giants",
  "New York Jets",
  "Philadelphia Eagles",
  "Pittsburgh Steelers",
  "San Francisco 49ers",
  "Seattle Seahawks",
  "Tampa Bay Buccaneers",
  "Tennessee Titans",
  "Washington Football Team",
  "Arizona Diamondbacks",
  "Atlanta Braves",
  "Baltimore Orioles ",
  "Boston Red Sox",
  "Chicago White Sox",
  "Chicago Cubs",
  "Cincinnati Reds",
  "Cleveland Indians",
  "Colorado Rockies",
  "Detroit Tigers",
  "Houston Astros",
  "Kansas City Royals",
  "Los Angeles Angels",
  "Los Angeles Dodgers",
  "Miami Marlins",
  "Milwaukee Brewers",
  "Minnesota Twins",
  "New York Yankees",
  "New York Mets",
  "Oakland Athletics",
  "Philadelphia Phillies",
  "Pittsburgh Pirates",
  "San Diego Padres",
  "San Francisco Giants",
  "Seattle Mariners",
  "St. Louis Cardinals",
  "Tampa Bay Rays",
  "Texas Rangers",
  "Toronto Blue Jays",
  "Washington Nationals",
  "AFC Bournemouth",
  "Arsenal",
  "Brighton & Hove Albion",
  "Burnley",
  "Cardiff City",
  "Chelsea",
  "Crystal Palace",
  "Everton",
  "Fulham",
  "Huddersfield Town",
  "Leicester City",
  "Liverpool",
  "Manchester City",
  "Manchester United",
  "Newcastle United",
  "Southampton",
  "Tottenham Hotspur",
  "Watford",
  "West Ham United",
  "Wolverhampton Wanderers",
  "Atlanta United",
  "Chicago Fire",
  "Columbus Crew SC",
  "DC United",
  "Montreal Impact",
  "New England Revolution",
  "New York City FC",
  "New York Red Bulls",
  "Orlando City SC",
  "Philadelphia Union",
  "Toronto FC",
  "Colorado Rapids",
  "FC Dallas",
  "Houston Dynamo",
  "LAFC",
  "LA Galaxy",
  "Minnesota United",
  "Portland Timbers",
  "Real Salt Lake",
  "San Jose Earthquakes",
  "Seattle Sounders",
  "Sporting Kansas City",
  "Vancouver Whitecaps",
  "Alavés",
  "Athletic Bilbao",
  "Atletico Madrid",
  "Barcelona",
  "Celta Vigo",
  "Eibar",
  "Espanyol",
  "Getafe",
  "Girona",
  "Huesca",
  "Leganes",
  "Levante",
  "Rayo Vallecano",
  "Real Betis",
  "Real Madrid",
  "Real Sociedad",
  "Real Valladolid",
  "Sevilla",
  "Valencia",
  "Villarreal",
  "AC Milan",
  "AS Roma",
  "Atalanta",
  "Bologna",
  "Cagliari",
  "Chievo Verona",
  "Empoli",
  "Fiorentina",
  "Frosinone",
  "Genoa",
  "Internazionale",
  "Juventus",
  "Lazio",
  "Napoli",
  "Parma",
  "Sampdoria",
  "Sassuolo",
  "SPAL",
  "Torino",
  "Udinese",
  "Bayer Leverkusen",
  "Bayern Munich",
  "Borussia Dortmund",
  "Borussia Monchengladbach",
  "Eintracht Frankfurt",
  "FC Augsburg",
  "Fortuna Dusseldorf",
  "Hannover",
  "Hertha Berlin",
  "Mainz",
  "Nurnberg",
  "RB Leipzig",
  "SC Freiburg",
  "Schalke",
  "TSG Hoffenheim",
  "VfB Stuttgart",
  "VfL Wolfsburg",
  "Werder Bremen",
  "Angers",
  "AS Monaco",
  "Bordeaux",
  "Caen",
  "Dijon FCO",
  "Guingamp",
  "Lille",
  "Lyon",
  "Marseille",
  "Montpellier",
  "Nantes",
  "Nice",
  "Nimes",
  "Paris Saint-Germain",
  "Saint-Etienne",
  "SC Amiens",
  "Stade de Reims",
  "Stade Rennes",
  "Strasbourg",
  "Toulouse",
  "BC Lions",
  "Calgary Stampeders",
  "Edmonton Elks",
  "Saskatchewan Roughriders",
  "Winnipeg Blue Bombers",
  "Hamilton Tiger-Cats",
  "Montreal Alouettes",
  "Ottawa Redblacks",
  "Toronto Argonauts",
  "Bellarmine Knights",
  "Central Arkansas Bears",
  "Eastern Kentucky Colonels",
  "Florida Gulf Coast Eagles",
  "Jacksonville Dolphins",
  "Jacksonville State Gamecocks",
  "Kennesaw State Owls",
  "Liberty Flames",
  "Lipscomb Bisons",
  "North Alabama Lions",
  "North Florida Ospreys",
  "Stetson Hatters",
  "Albany Great Danes",
  "Binghamton Bearcats",
  "Hartford Hawks",
  "Maine Black Bears",
  "NJIT Highlanders",
  "New Hampshire Wildcats",
  "Stony Brook Seawolves",
  "UMBC Retrievers",
  "UMass Lowell River Hawks",
  "Vermont Catamounts",
  "Cincinnati Bearcats",
  "East Carolina Pirates",
  "Houston Cougars",
  "Memphis Tigers",
  "SMU Mustangs",
  "South Florida Bulls",
  "Temple Owls",
  "Tulane Green Wave",
  "Tulsa Golden Hurricane",
  "UCF Knights",
  "Wichita State Shockers",
  "Davidson Wildcats",
  "Dayton Flyers",
  "Duquesne Dukes",
  "Fordham Rams",
  "George Mason Patriots",
  "George Washington Colonials",
  "La Salle Explorers",
  "Rhode Island Rams",
  "Richmond Spiders",
  "Saint Joseph's Hawks",
  "Saint Louis Billikens",
  "St. Bonaventure Bonnies",
  "UMass Minutemen",
  "VCU Rams",
  "Boston College Eagles",
  "Clemson Tigers",
  "Duke Blue Devils",
  "Florida State Seminoles",
  "Georgia Tech Yellow Jackets",
  "Louisville Cardinals",
  "Miami Hurricanes",
  "NC State Wolfpack",
  "North Carolina Tar Heels",
  "Notre Dame Fighting Irish",
  "Pittsburgh Panthers",
  "Syracuse Orange",
  "Virginia Cavaliers",
  "Virginia Tech Hokies",
  "Wake Forest Demon Deacons",
  "Baylor Bears",
  "Iowa State Cyclones",
  "Kansas Jayhawks",
  "Kansas State Wildcats",
  "Oklahoma Sooners",
  "Oklahoma State Cowboys",
  "TCU Horned Frogs",
  "Texas Longhorns",
  "Texas Tech Red Raiders",
  "West Virginia Mountaineers",
  "Butler Bulldogs",
  "Creighton Bluejays",
  "DePaul Blue Demons",
  "Georgetown Hoyas",
  "Marquette Golden Eagles",
  "Providence Friars",
  "Seton Hall Pirates",
  "St. John's Red Storm",
  "UConn Huskies",
  "Villanova Wildcats",
  "Xavier Musketeers",
  "Eastern Washington Eagles",
  "Idaho State Bengals",
  "Idaho Vandals",
  "Montana Grizzlies",
  "Montana State Bobcats",
  "Northern Arizona Lumberjacks",
  "Northern Colorado Bears",
  "Portland State Vikings",
  "Sacramento State Hornets",
  "Southern Utah Thunderbirds",
  "Weber State Wildcats",
  "Campbell Fighting Camels",
  "Charleston Southern Buccaneers",
  "Gardner-Webb Runnin' Bulldogs",
  "Hampton Pirates",
  "High Point Panthers",
  "Longwood Lancers",
  "North Carolina A&T Aggies",
  "Presbyterian Blue Hose",
  "Radford Highlanders",
  "South Carolina Upstate Spartans",
  "UNC Asheville Bulldogs",
  "Winthrop Eagles",
  "Illinois Fighting Illini",
  "Indiana Hoosiers",
  "Iowa Hawkeyes",
  "Maryland Terrapins",
  "Michigan State Spartans",
  "Michigan Wolverines",
  "Minnesota Golden Gophers",
  "Nebraska Cornhuskers",
  "Northwestern Wildcats",
  "Ohio State Buckeyes",
  "Penn State Nittany Lions",
  "Purdue Boilermakers",
  "Rutgers Scarlet Knights",
  "Wisconsin Badgers",
  "CSU Bakersfield Roadrunners",
  "CSU Fullerton Titans",
  "CSU Northridge Matadors",
  "Cal Poly Mustangs",
  "Hawai'i Rainbow Warriors",
  "Long Beach State Beach",
  "UC Davis Aggies",
  "UC Irvine Anteaters",
  "UC Riverside Highlanders",
  "UC San Diego Tritons",
  "UC Santa Barbara Gauchos",
  "Charleston Cougars",
  "Delaware Blue Hens",
  "Drexel Dragons",
  "Elon Phoenix",
  "Hofstra Pride",
  "James Madison Dukes",
  "Northeastern Huskies",
  "Towson Tigers",
  "UNC Wilmington Seahawks",
  "William & Mary Tribe",
  "Charlotte ers",
  "Florida Atlantic Owls",
  "Florida International Panthers",
  "Louisiana Tech Bulldogs",
  "Marshall Thundering Herd",
  "Middle Tennessee Blue Raiders",
  "North Texas Mean Green",
  "Old Dominion Monarchs",
  "Rice Owls",
  "Southern Miss Golden Eagles",
  "UAB Blazers",
  "UTEP Miners",
  "UTSA Roadrunners",
  "Western Kentucky Hilltoppers",
  "Cleveland State Vikings",
  "Detroit Mercy Titans",
  "Green Bay Phoenix",
  "IUPUI Jaguars",
  "Milwaukee Panthers",
  "Northern Kentucky Norse",
  "Oakland Golden Grizzlies",
  "Purdue Fort Wayne Mastodons",
  "Robert Morris Colonials",
  "UIC Flames",
  "Wright State Raiders",
  "Youngstown State Penguins",
  "Brown Bears",
  "Columbia Lions",
  "Cornell Big Red",
  "Dartmouth Big Green",
  "Harvard Crimson",
  "Pennsylvania Quakers",
  "Princeton Tigers",
  "Yale Bulldogs",
  "Canisius Golden Griffins",
  "Fairfield Stags",
  "Iona Gaels",
  "Manhattan Jaspers",
  "Marist Red Foxes",
  "Monmouth Hawks",
  "Niagara Purple Eagles",
  "Quinnipiac Bobcats",
  "Rider Broncs",
  "Saint Peter's Peacocks",
  "Siena Saints",
  "Akron Zips",
  "Ball State Cardinals",
  "Bowling Green Falcons",
  "Buffalo Bulls",
  "Central Michigan Chippewas",
  "Eastern Michigan Eagles",
  "Kent State Golden Flashes",
  "Miami (OH) Redhawks",
  "Northern Illinois Huskies",
  "Ohio Bobcats",
  "Toledo Rockets",
  "Western Michigan Broncos",
  "Coppin State Eagles",
  "Delaware State Hornets",
  "Howard Bison",
  "Maryland-Eastern Shore Hawks",
  "Morgan State Bears",
  "Norfolk State Spartans",
  "North Carolina Central Eagles",
  "South Carolina State Bulldogs",
  "Bradley Braves",
  "Drake Bulldogs",
  "Evansville Purple Aces",
  "Illinois State Redbirds",
  "Indiana State Sycamores",
  "Loyola Chicago Ramblers",
  "Missouri State Bears",
  "Northern Iowa Panthers",
  "Southern Illinois Salukis",
  "Valparaiso Beacons",
  "Air Force Falcons",
  "Boise State Broncos",
  "Colorado State Rams",
  "Fresno State Bulldogs",
  "Nevada Wolf Pack",
  "New Mexico Lobos",
  "San Diego State Aztecs",
  "San José State Spartans",
  "UNLV Rebels",
  "Utah State Aggies",
  "Wyoming Cowboys",
  "Bryant Bulldogs",
  "Central Connecticut Blue Devils",
  "Fairleigh Dickinson Knights",
  "Long Island University Sharks",
  "Merrimack Warriors",
  "Mount St. Mary's Mountaineers",
  "Sacred Heart Pioneers",
  "St. Francis (BKN) Terriers",
  "St. Francis (PA) Red Flash",
  "Wagner Seahawks",
  "Austin Peay Governors",
  "Belmont Bruins",
  "Eastern Illinois Panthers",
  "Morehead State Eagles",
  "Murray State Racers",
  "SIU Edwardsville Cougars",
  "Southeast Missouri State Redhawks",
  "Tennessee State Tigers",
  "Tennessee Tech Golden Eagles",
  "UT Martin Skyhawks",
  "Arizona State Sun Devils",
  "Arizona Wildcats",
  "California Golden Bears",
  "Colorado Buffaloes",
  "Oregon Ducks",
  "Oregon State Beavers",
  "Stanford Cardinal",
  "UCLA Bruins",
  "USC Trojans",
  "Utah Utes",
  "Washington Huskies",
  "Washington State Cougars",
  "American University Eagles",
  "Army Black Knights",
  "Boston University Terriers",
  "Bucknell Bison",
  "Colgate Raiders",
  "Holy Cross Crusaders",
  "Lafayette Leopards",
  "Lehigh Mountain Hawks",
  "Loyola (MD) Greyhounds",
  "Navy Midshipmen",
  "Alabama Crimson Tide",
  "Arkansas Razorbacks",
  "Auburn Tigers",
  "Florida Gators",
  "Georgia Bulldogs",
  "Kentucky Wildcats",
  "LSU Tigers",
  "Mississippi State Bulldogs",
  "Missouri Tigers",
  "Ole Miss Rebels",
  "South Carolina Gamecocks",
  "Tennessee Volunteers",
  "Texas A&M Aggies",
  "Vanderbilt Commodores",
  "Chattanooga Mocs",
  "East Tennessee State Buccaneers",
  "Furman Paladins",
  "Mercer Bears",
  "Samford Bulldogs",
  "The Citadel Bulldogs",
  "UNC Greensboro Spartans",
  "VMI Keydets",
  "Western Carolina Catamounts",
  "Wofford Terriers",
  "Houston Baptist Huskies",
  "Incarnate Word Cardinals",
  "McNeese Cowboys",
  "New Orleans Privateers",
  "Nicholls Colonels",
  "Northwestern State Demons",
  "SE Louisiana Lions",
  "Texas A&M-CC Islanders",
  "Alabama A&M Bulldogs",
  "Alabama State Hornets",
  "Alcorn State Braves",
  "Arkansas-Pine Bluff Golden Lions",
  "Bethune-Cookman Wildcats",
  "Florida A&M Rattlers",
  "Grambling Tigers",
  "Jackson State Tigers",
  "Mississippi Valley State Delta Devils",
  "Prairie View A&M Panthers",
  "Southern Jaguars",
  "Texas Southern Tigers",
  "Denver Pioneers",
  "Kansas City Roos",
  "North Dakota Fighting Hawks",
  "North Dakota State Bison",
  "Omaha Mavericks",
  "Oral Roberts Golden Eagles",
  "South Dakota Coyotes",
  "South Dakota State Jackrabbits",
  "St. Thomas - Minnesota Tommies",
  "Western Illinois Leathernecks",
  "Appalachian State Mountaineers",
  "Arkansas State Red Wolves",
  "Coastal Carolina Chanticleers",
  "Georgia Southern Eagles",
  "Georgia State Panthers",
  "Little Rock Trojans",
  "Louisiana Ragin' Cajuns",
  "South Alabama Jaguars",
  "Texas State Bobcats",
  "Troy Trojans",
  "UL Monroe Warhawks",
  "UT Arlington Mavericks",
  "BYU Cougars",
  "Gonzaga Bulldogs",
  "Loyola Marymount Lions",
  "Pacific Tigers",
  "Pepperdine Waves",
  "Portland Pilots",
  "Saint Mary's Gaels",
  "San Diego Toreros",
  "San Francisco Dons",
  "Santa Clara Broncos",
  "Abilene Christian Wildcats",
  "California Baptist Lancers",
  "Chicago State Cougars",
  "Dixie State Trailblazers",
  "Grand Canyon Antelopes",
  "Lamar Cardinals",
  "New Mexico State Aggies",
  "Sam Houston Bearkats",
  "Seattle U Redhawks",
  "Stephen F. Austin Lumberjacks",
  "Tarleton Texans",
  "UT Rio Grande Valley Vaqueros",
  "Utah Valley Wolverines",
];
