// reformat and add soccer and countries
const allTeams = {
  "Anaheim Ducks": "Hockey",
  "Arizona Coyotes": "Hockey",
  "Boston Bruins": "Hockey",
  "Buffalo Sabres": "Hockey",
  "Calgary Flames": "Hockey",
  "Carolina Hurricanes": "Hockey",
  "Chicago Blackhawks": "Hockey",
  "Colorado Avalanche": "Hockey",
  "Columbus Blue Jackets": "Hockey",
  "Dallas Stars": "Hockey",
  "Detroit Red Wings": "Hockey",
  "Edmonton Oilers": "Hockey",
  "Florida Panthers": "Hockey",
  "Los Angeles Kings": "Hockey",
  "Minnesota Wild": "Hockey",
  "Montreal Canadiens": "Hockey",
  "Nashville Predators": "Hockey",
  "New Jersey Devils": "Hockey",
  "New York Islanders": "Hockey",
  "New York Rangers": "Hockey",
  "Ottawa Senators": "Hockey",
  "Philadelphia Flyers": "Hockey",
  "Pittsburgh Penguins": "Hockey",
  "San Jose Sharks": "Hockey",
  "Seattle Kraken": "Hockey",
  "St Louis Blues": "Hockey",
  "Tampa Bay Lightning": "Hockey",
  "Toronto Maple Leafs": "Hockey",
  "Vancouver Canucks": "Hockey",
  "Vegas Golden Knights": "Hockey",
  "Washington Capitals": "Hockey",
  "Winnipeg Jets": "Hockey",

  "Atlanta Hawks": "Basketball",
  "Boston Celtics": "Basketball",
  "Brooklyn Nets": "Basketball",
  "Charlotte Hornets": "Basketball",
  "Chicago Bulls": "Basketball",
  "Cleveland Cavaliers": "Basketball",
  "Dallas Mavericks": "Basketball",
  "Denver Nuggets": "Basketball",
  "Detroit Pistons": "Basketball",
  "Golden State Warriors": "Basketball",
  "Houston Rockets": "Basketball",
  "Indiana Pacers": "Basketball",
  "Los Angeles Clippers": "Basketball",
  "Los Angeles Lakers": "Basketball",
  "Memphis Grizzlies": "Basketball",
  "Miami Heat": "Basketball",
  "Milwaukee Bucks": "Basketball",
  "Minnesota Timberwolves": "Basketball",
  "New Orleans Pelicans": "Basketball",
  "New York Knicks": "Basketball",
  "Oklahoma City Thunder": "Basketball",
  "Orlando Magic": "Basketball",
  "Philadelphia 76ers": "Basketball",
  "Phoenix Suns": "Basketball",
  "Portland Trail Blazers": "Basketball",
  "Sacramento Kings": "Basketball",
  "San Antonio Spurs": "Basketball",
  "Toronto Raptors": "Basketball",
  "Utah Jazz": "Basketball",
  "Washington Wizards": "Basketball",

  "Arizona Cardinals": "Football",
  "Atlanta Falcons": "Football",
  "Baltimore Ravens": "Football",
  "Buffalo Bills": "Football",
  "Carolina Panthers": "Football",
  "Chicago Bears": "Football",
  "Cincinnati Bengals": "Football",
  "Cleveland Browns": "Football",
  "Dallas Cowboys": "Football",
  "Denver Broncos": "Football",
  "Detroit Lions": "Football",
  "Green Bay Packers": "Football",
  "Houston Texans": "Football",
  "Indianapolis Colts": "Football",
  "Jacksonville Jaguars": "Football",
  "Kansas City Chiefs": "Football",
  "Las Vegas Raiders": "Football",
  "Los Angeles Chargers": "Football",
  "Los Angeles Rams": "Football",
  "Miami Dolphins": "Football",
  "Minnesota Vikings": "Football",
  "New England Patriots": "Football",
  "New Orleans Saints": "Football",
  "New York Giants": "Football",
  "New York Jets": "Football",
  "Philadelphia Eagles": "Football",
  "Pittsburgh Steelers": "Football",
  "San Francisco 49ers": "Football",
  "Seattle Seahawks": "Football",
  "Tampa Bay Buccaneers": "Football",
  "Tennessee Titans": "Football",
  "Washington Football Team": "Football",

  "Arizona Diamondbacks": "Baseball",
  "Atlanta Braves": "Baseball",
  "Baltimore Orioles ": "Baseball",
  "Boston Red Sox": "Baseball",
  "Chicago White Sox": "Baseball",
  "Chicago Cubs": "Baseball",
  "Cincinnati Reds": "Baseball",
  "Cleveland Indians": "Baseball",
  "Colorado Rockies": "Baseball",
  "Detroit Tigers": "Baseball",
  "Houston Astros": "Baseball",
  "Kansas City Royals": "Baseball",
  "Los Angeles Angels": "Baseball",
  "Los Angeles Dodgers": "Baseball",
  "Miami Marlins": "Baseball",
  "Milwaukee Brewers": "Baseball",
  "Minnesota Twins": "Baseball",
  "New York Yankees": "Baseball",
  "New York Mets": "Baseball",
  "Oakland Athletics": "Baseball",
  "Philadelphia Phillies": "Baseball",
  "Pittsburgh Pirates": "Baseball",
  "San Diego Padres": "Baseball",
  "San Francisco Giants": "Baseball",
  "Seattle Mariners": "Baseball",
  "St. Louis Cardinals": "Baseball",
  "Tampa Bay Rays": "Baseball",
  "Texas Rangers": "Baseball",
  "Toronto Blue Jays": "Baseball",
  "Washington Nationals": "Baseball",
};

console.log(JSON.stringify(Object.keys(allTeams)));
